### ISSUE TITLE
Chapter 2: problem with interface in functionGeneric.ts

### ISSUE THREAD

**Issue by FedeHC** [PacktPublishing/Full-Stack-React-TypeScript-and-Node#10]
Hi there.

I don't know if this problem only appears to me, but I would like to comment it anyway...

In _functionGeneric.ts_ in chapter 2 the concept of generics is introduced. The first half of the code is introduced like this:

```typescript
function getLength<T>(arg: T): number {
  if(arg.hasOwnProperty("length")) {
    return arg["length"];
  }
  return 0;
}

console.log(getLength<number>(22));
console.log(getLength("Hello world."));
```

So far so good.

But in the second part, when I have commented all the previous code as instructed and enter the following one...

```typescript
interface HasLength {
  length: number;
}

function getLength<T extends HasLength>(arg: T): number {
  return arg.length;
}

console.log(getLength<number>(22));
console.log(getLength("Hello world."));
```
... then I get this error:

`Type 'number' does not satisfy the constraint 'HasLength'.  ts(2344)` 

Maybe I'm guessing but.... Is it possible that some change during Typescript 3.8 makes it impossible to implement an interface in this way now? Or maybe I'm missing something?

By the way, I'm using VScode in Linux Mint 20.1 with Typescript v3.8.3 and node v14.16.1 installed globally (both).

**Comment by jsoneaday** [comment]
@FedeHC Hello thanks for you question. I am the author.

The error you are seeing is actually not a failure or bug, but the correct thing that should happen is happening. Let me explain. 

I believe in this chapter I explain that TypeScript is not so concerned about a type's name as it is about its shape. So in the case of the getLength function that was updated, getLength<T extends HasLength>(arg: T), what is happening is that we are telling the TypeScript compiler that we are about to use a parameter, arg, that is of _some type_ but that type **must** have a member called _length_. So in other words we are constraining which specific types we can use to only those that have a member called _length_, and we do this by using <T extends HasLength>. You can read this part of the code as, "I can take any type, but only if it has _length_".

Therefore if you look at the number type inside of JavaScript, this type never have a member called length. It simply does not exist for numbers. So when we try and call getLength<number> the TypeScript compiler immediately complains saying "Hey you cannot use a number type here because numbers don't have a length member". In other words I deliberately caused an error to occur so that I could show you how TypeScript can help you when you make a mistake. 

However when we use a string (and by the way we don't need to call getLength<string>, by simply passing a string as the arg parameter the TypeScript compiler knows what we mean) TypeScript is happy and does not complain, because all strings have a member called length. And if you re-read the paragraph after this code you will see that I pretty much say the same thing.

I hope this helps. Please let me know if you have other questions. Thanks for purchasing the book and I wish you well.

**Comment by FedeHC** [comment]
Ohh, I didn't realize that was the intention! Thanks for your detailed explanation. :)

I think we can close this issue then.
