### ISSUE TITLE
Chapter 9 - Page 308

### ISSUE THREAD

**Issue by linhtch90** [PacktPublishing/Full-Stack-React-TypeScript-and-Node#14]
pubsub is not a part of GqlContext

![image](https://user-images.githubusercontent.com/67230802/123786180-9867c980-d903-11eb-9d89-d05788b6a0d2.png)

**Comment by jsoneaday** [comment]
Hello @linhtch90 which chapter are you looking at. When I search chapter 17 resolvers.ts file I see no reference to pubsub.

**Comment by linhtch90** [comment]
Sir, it is Chapter 9, page 308.

**Comment by jsoneaday** [comment]
GqlContext is an interface defined in the file GqlContext.ts (this is the TypeScript file). It is not part of Apollo. I checked that file and the definition is certainly there as shown by the screenshot. Also as you can imagine it would seem unlikely a failure of this magnitude would have gone uncaught, because the example in the book would then not work. 

Have you compiled your code from TypeScript into Javascript first before running? Can you check what is inside the GqlContext.js file? In order to follow along the book, it is not enough to simply download the files--you must also compile the code into Javascript as the book examples show. When I look at the source code on Github, https://github.com/PacktPublishing/Full-Stack-React-TypeScript-and-Node/blob/master/Chap9/graphql-schema/GqlContext.js, the GqlContext.js file is not the final version of the file. Which is why it does not have the pubsub definition in it.

![image](https://user-images.githubusercontent.com/1474935/123800848-b3145100-d8b7-11eb-80c0-1992b7039935.png)

**Comment by jsoneaday** [comment]
I am closing this issue as I've not heard back and the response resolves the issue.

**Comment by linhtch90** [comment]
Thank you, sir! Your answer solved the problem.
