### ISSUE TITLE
I can't change from Latest to any other category from Chap15 page: 508

### ISSUE THREAD

**Issue by malikmouhiidine** [PacktPublishing/Full-Stack-React-TypeScript-and-Node#16]
when trying to click on one of the left menu categories it changes for a second and return to the Latest
[Note: i have the same code as the source code](https://github.com/PacktPublishing/Full-Stack-React-TypeScript-and-Node/blob/master/Chap15/super-forum-client/src/components/areas/main/Main.tsx)

https://user-images.githubusercontent.com/73129654/130817020-bed31ad1-bae4-4b03-8739-29c48b8a8249.mp4

**Comment by jsoneaday** [comment]
Hello I am the author. I downloaded the source code fresh for chap15 and setup a fresh Postgres server and Redis server on docker, as I don't have the cloud access anymore--but that does not matter for your issue. I've made no code changes other than to remove the Redis password in index.ts, since I don't use it in my docker image. It works without issue for me. The video shows the app running live in debug mode with no significant code changes.

This issue is arising from a change of some kind that you have made. 

The issue has to do with your React state setup. Let me give you some friendly advice. Even if there was an issue in the code, for something of this nature you should try and resolve the issue yourself using google and your own hard effort. The reason why it is important for you to resolve it, is that as a React dev you will be working with and fixing state issues all day long. I wish you luck. 

https://user-images.githubusercontent.com/1474935/131196336-601893d2-d854-4ad0-b4b3-2f238c4f9732.mov

**Comment by malikmouhiidine** [comment]
Before closing the issue I just wanna say thank you for the effort that you made in this book I find it really useful and I'll be excited to see more books from you.

**Comment by jsoneaday** [comment]
Thank you. I sincerely hope all your dreams come true and you have a successful career as a developer

**Comment by malikmouhiidine** [comment]
Just to make sure can u try to go to the root url http://localhost:3000/ then clicking on one of the categories because there when the problem happens for me, but if you have to setup the environment again never mind.
