### ISSUE TITLE
Chapter 6: DisplayText type void not assignable to Button element

### ISSUE THREAD

**Issue by darrenbarklie** [PacktPublishing/Full-Stack-React-TypeScript-and-Node#18]
```
/Users/daz/Code/_learn/fullstack-react-typescript-node/06/ejected-app/src/DisplayText.tsx
TypeScript error in /Users/daz/Code/_learn/fullstack-react-typescript-node/06/ejected-app/src/DisplayText.tsx(46,44):
Type '(e: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void' is not assignable to type 'MouseEventHandler<HTMLButtonElement>'.
  Types of parameters 'e' and 'event' are incompatible.
    Type 'MouseEvent<HTMLButtonElement, MouseEvent>' is not assignable to type 'MouseEvent<HTMLButtonElement, MouseEvent<Element, MouseEvent>>'.
      Type 'MouseEvent' is missing the following properties from type 'MouseEvent<Element, MouseEvent>': nativeEvent, isDefaultPrevented, isPropagationStopped, persist  TS2322

    44 | 
    45 |       <div>
  > 46 |         <button data-testid="input-submit" onClick={onClickShowMsg}>
       |                                            ^
    47 |           Show Message
    48 |         </button>
    49 |       </div>
```
Hi, I encountered the above error, while following the page 184 example verbatim.

Managed to resolve it, thanks to [this answer](https://github.com/apollographql/react-apollo/issues/1841#issuecomment-376299233), but don't understand why `{onClickShowMsg as any}` is required.  Could I get further guidance or a pointer to documentation for this?

Many thanks in advance.

**Comment by mikerourke** [comment]
Hi @darrenbarklie, I apologize for the delayed response. I'm not encountering this error on my end. Did you upgrade any of the dependencies?

**Comment by jsoneaday** [comment]
Please note you should be using the same versions for your dependencies, and not just have the same code, because as versions change they can sometimes change behavior or type signatures. This is particularly true for TypeScript.

As for the issue, the typescript config file was set to force explicit use of any--as opposed to implicit. What I suspect is going on is that you've upgraded to either a newer typescript version or react and the event handler signatures have changed somewhat. By giving it an any type you're basically making it open to any type. The book had a small section, discussing the usage of the any type and how it should be avoided but can be helpful in a pinch.

If you hover over the onClick handler of your button element (_NOT_ the onClickShowMsg function) you should see the exact function signature needed for _your_ local version of typescript and react. If you switch to that signature you will be able to get rid of the any and it should work. Hope this helps.

**Comment by jsoneaday** [comment]
By way it's pretty cool you're into Solana. That blockchain has a ton of potential.

**Comment by darrenbarklie** [comment]
Hi @mikerourke, thanks for the guidance on this.

I should have been more considered with the dependencies used, so appreciate how this might have generated the discrepancy. I'm now more familiar with hovering on elements to interpret function signatures, appreciate this tip.

I've successfully progressed through the Redux and React Router chapter.  Took a little time to map to the new RRv6 API, but I'm quite used to the continued rewrites of this package!

@jsoneaday I'm very interested to learn of your DeChat project on GitCoin. Is it under active development?

My ambition for this year is to level up toward a React, TypeScript, Rust stack to be able to build on Solana.  I've still a lot to learn, but find Distributed IDs and Zero Knowledge Proofs interesting to equip with the utility and speed of Solana.

**Comment by jsoneaday** [comment]
Hey Darren its great to hear your using my book to achieve your goals.

Yes DeChat is still in active development and will use a mix of technologies including React, SwiftUI, and Rust. If you’re interested you can follow the project”s Twitter @dechataap.

Also since you’re learning Solana you’ll need to learn Rust Smart Contracts. Try my YouTube for that https://youtube.com/playlist?list=PL41Cw3fN3CfdbmhgxADwyDyIoDrxc22v2
