### ISSUE TITLE
CSS class selectors used by ThreadCard.tsx are missing

### ISSUE THREAD

**Issue by jxvargas** [PacktPublishing/Full-Stack-React-TypeScript-and-Node#3]
On Chapter 12, the component **ThreadCard.tsx** makes use of the following CSS classes:

- content-header
- link-txt
- username-header
- question

However, none of them can be found neither in *ThreadCard.css* nor in *App.css*

**Comment by jsoneaday** [comment]
Hello @jxvargas sorry for the delayed response. I am the author of the book. I believe the issue is that these CSS attributes were no longer used but not removed from the source code. I apologize for that.
I'm trying to use the searcher on my Kindle copy of the book, in order to verify, but it does not work for some reason. But I do recall that those later chapters were evolving where the code started simple and got transformed, sometimes quite severely, later down the road.

Let me ask you is there some item that style wise does not look right and you cannot figure out how to get it the way you want? I'm happy to help. Let me know.

**Comment by jxvargas** [comment]
Hello @jsoneaday, thanks for your reply.

The figures on the chapter seem consistent with the style of the pages/components generated by the code, so that confirms what you just mentioned about those CSS attributes not  being used/needed.  

The reference to those extra CSS classes led me to think that their style would be somehow enhanced, but the components look good as they are anyway. I'll proceed to close this issue. 

PS: Great book by the way...

**Comment by jsoneaday** [comment]
Thanks for confirming. I hope you're enjoying the book. Let me know if you have any other questions.
________________________________
