### ISSUE TITLE
Problem with useParams

### ISSUE THREAD

**Issue by danielgara** [PacktPublishing/Full-Stack-React-TypeScript-and-Node#9]
Dear author, please check the next line.

https://github.com/PacktPublishing/Full-Stack-React-TypeScript-and-Node/blob/2ab64436ec9081a5c2cad4040890761a2b0911b3/Chap7/try-react-router/src/ScreenC.tsx#L17

I had to change this line:

```
const { userid } = useParams();
```

To this format, in order to work for me:

```
const { userid } = useParams<{ userid: string }>();
```

**Comment by jsoneaday** [comment]
Thank you for the post. When you say does not work, does your app compile and run? Since the application does compile and run  for me with unmodified code, I would not bother annotating code for something like this. I understand that you want to be as statically typed as possible, but in this case there is no real benefit. The urls in a large app will be many and the parameters will also be completely arbitrary. There is little to no benefit in trying to type this information.

I've loaded the site for this chapter on that specific url and the id is being found and used (I've not modified any code).
![image](https://user-images.githubusercontent.com/1474935/115452349-51b37000-a1ec-11eb-888e-4358236d2e8d.png)

**Comment by danielgara** [comment]
@jsoneaday It didn't compile. So, it didn't allow me to run the code. 

![error](https://i.ibb.co/kxF96r1/Captura.png)

I think it is because of the TypeScript version. In my package.json it is 4.2.4, but in the project I think it is 3.*
**Check this link:** https://stackoverflow.com/questions/63660520/typescript-error-after-upgrading-version-4-useparams-from-react-router-dom-pr

Thank you!

**Comment by danielgara** [comment]
**Note:**
The error happened because I followed the book instructions and I used the _create-react-project_ command (so obviously some dependencies versions are newer than the dependencies in this repo). If someone uses this repo directly I think he/she won't have this issue. 

So, maybe this is not an issue. Just a suggestion I think.

**Comment by jsoneaday** [comment]
> @jsoneaday It didn't compile. So, it didn't allow me to run the code.
> 
> ![error](https://camo.githubusercontent.com/7eb1e570b2d0df436f819685755ac28c563c72a2c00b141ff61d4e674a415efa/68747470733a2f2f692e6962622e636f2f6b7846393672312f436170747572612e706e67)
> 
> I think it is because of the TypeScript version. In my package.json it is 4.2.4, but in the project I think it is 3.*
> **Check this link:** https://stackoverflow.com/questions/63660520/typescript-error-after-upgrading-version-4-useparams-from-react-router-dom-pr
> 
> Thank you!

That makes sense. Sometimes they get stricter between versions 

Please post again if you have further questions
